month2digit = {"Jan" : "1",
               "Feb" : "2",
               "Mar" : "3",
               "Apr" : "4",
               "May" : "5",
               "Jun" : "6",
               "Jul" : "7",
               "Aug" : "8",
               "Sep" : "9",
               "Oct" : "10",
               "Nov" : "11",
               "Dec" : "12"}


col2filename = {"summary" : "summary",
                "cash_flow" : "cash_flow",
                "income_statement" : "income_statement",
                "balance_sheet" : "balance_sheet",
                "statistics" : "statistics",
                "Stock Splits" : "stock_split",
                "stock_split" : "stock_split",
                "Dividends Only" : "dividend",
                "dividend" : "dividend",
                "history" : "history",
                "tmp" : "tmp",
                "profile" : "profile"}
"""

                "Symbol" : "profile",
                "Name" : "profile",
                "IPOyear" : "profile",
                "Sector" : "profile",
                "Industry" : "profile",
                "Exchange" : "profile",
                "IS_STOCK" : "profile",

                "Market Cap" : "summary",
                "Shares Outstanding" : "summary",
                "% Held by Insiders" : "summary",
                "% Held by Institutions" : "summary",
                "Forward Annual Dividend Rate" : "summary",
                "Forward Annual Dividend Yield" : "summary",
                "Trailing Annual Dividend Rate" : "summary",
                "Trailing Annual Dividend Yield" : "summary",
                "5 Year Average Dividend Yield" : "summary",
                "Dividend Date" : "summary",
                "Ex-Dividend Date" : "summary",
                "Payout Ratio" : "summary",
                "Profit Margin" : "summary",
                "Operating Margin" : "summary",
                "Return on Assets" : "summary",
                "Return on Equity" : "summary",
                "Revenue Per Share" : "summary",
                "Diluted EPS" : "summary",
                "Total Cash Per Share" : "summary",
                "Total Debt" : "summary",
                "Current Ratio" : "summary",
                "Fiscal Year Ends" : "summary",

                "CashCashEquivalentsAndShortTermInvestments" : "balance_sheet",
                "CashAndCashEquivalents" : "balance_sheet",
                "CurrentLiabilities" : "balance_sheet",
                "LongTermDebt" : "balance_sheet",
                "CurrentAssets" : "balance_sheet",
                "CurrentLiabilities" : "balance_sheet",
                "TotalAssets" : "balance_sheet",

                "TotalRevenue" : "income_statement",
                "GrossProfit" : "income_statement",
                "CostOfRevenue" : "income_statement",
                "OperatingIncome" : "income_statement",
                "OperatingRevenue" : "income_statement",
                "OperatingExpense" : "income_statement",
                "OtherOperatingExpenses" : "income_statement",
                "SellingGeneralAndAdministration" : "income_statement",
                "ResearchAndDevelopment" : "income_statement",
                "NetIncome" : "income_statement",
                "DilutedEPS" : "income_statement",
                "EBIT" : "income_statement",

                "FreeCashFlow" : "cash_flow",
                "RepurchaseOfCapitalStock" : "cash_flow",
                "CashDividendsPaid" : "cash_flow",
                "OperatingCashFlow" : "cash_flow",

                "PeRatio" : "statistics",
                "ForwardPeRatio" : "statistics",
                "PegRatio" : "statistics",
                "PsRatio" : "statistics",
                "PbRatio" : "statistics",
                "EnterpriseValue" : "statistics",
                "EnterprisesValueRevenueRatio" : "statistics",
                "MarketCap" : "statistics",
                "Fiscal Year Ends" : "statistics",
                "Most Recent Quarter" : "statistics",
                "Profit Margin" : "statistics",
                "Operating Margin" : "statistics",
                "Return on Assets" : "statistics",
                "Return on Equity" : "statistics",
                "Revenue" : "statistics",
                "Revenue Per Share" : "statistics",
                "Quarterly Revenue Growth" : "statistics",
                "Gross Profit" : "statistics",
                "EBITDA" : "statistics",
                "Net Income Avi to Common" : "statistics",
                "Diluted EPS" : "statistics",
                "Quarterly Earnings Growth" : "statistics",
                "Total Cash" : "statistics",
                "Total Cash Per Share" : "statistics",
                "Total Debt" : "statistics",
                "Total Debt/Equity" : "statistics",
                "Current Ratio" : "statistics",
                "Book Value Per Share" : "statistics",
                "Operating Cash Flow" : "statistics",
                "Levered Free Cash Flow" : "statistics",

                "CurrentPrice" : "historical_data",
                "Open" : "historical_data",
                "High" : "historical_data",
                "Low" : "historical_data",
                "Close" : "historical_data",
                "Adj Close" : "historical_data",
                "Volume" : "historical_data"}


col2type = {"Symbol" : "string",
            "Name" : "string",
            "Sector" : "string",
            "Industry" : "string",
            "Exchange" : "string",

            "Date" : "datetime",
            "Fiscal Year Ends" : "datetime",

            "IS_STOCK" : "bool",

            "IPOyear" : "numeric",
            "Market Cap" : "numeric",
            "Shares Outstanding" : "numeric",
            "% Held by Insiders" : "numeric",
            "% Held by Institutions" : "numeric",
            "Forward Annual Dividend Rate" : "numeric",
            "Forward Annual Dividend Yield" : "numeric",
            "Trailing Annual Dividend Rate" : "numeric",
            "Trailing Annual Dividend Yield" : "numeric",
            "5 Year Average Dividend Yield" : "numeric",
            "Dividend Date" : "numeric",
            "Ex-Dividend Date" : "numeric",
            "Payout Ratio" : "numeric",
            "Profit Margin" : "numeric",
            "Operating Margin" : "numeric",
            "Return on Assets" : "numeric",
            "Return on Equity" : "numeric",
            "Revenue Per Share" : "numeric",
            "Diluted EPS" : "numeric",
            "Total Cash Per Share" : "numeric",
            "Total Debt" : "numeric",
            "Current Ratio" : "numeric",
            "FreeCashFlow" : "numeric",
            "RepurchaseOfCapitalStock" : "numeric",
            "CashDividendsPaid" : "numeric",
            "CashCashEquivalentsAndShortTermInvestments" : "numeric",
            "CashAndCashEquivalents" : "numeric",
            "CurrentLiabilities" : "numeric",
            "LongTermDebt" : "numeric",
            "CurrentAssets" : "numeric",
            "CurrentLiabilities" : "numeric",
            "TotalRevenue" : "numeric",
            "GrossProfit" : "numeric",
            "CostOfRevenue" : "numeric",
            "OperatingIncome" : "numeric",
            "OperatingRevenue" : "numeric",
            "OperatingExpense" : "numeric",
            "SellingGeneralAndAdministration" : "numeric",
            "ResearchAndDevelopment" : "numeric",
            "NetIncome" : "numeric",
            "DilutedEPS" : "numeric",
            "EBIT" : "numeric",
            "PeRatio" : "numeric",
            "PegRatio" : "numeric",
            "PsRatio" : "numeric",
            "PbRatio" : "numeric",
            "CurrentPrice" : "numeric",
            "Open" : "numeric",
            "High" : "numeric",
            "Low" : "numeric",
            "Close" : "numeric",
            "Adj Close" : "numeric",
            "Volume" : "numeric"}
"""
